# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_CAMERA_STAR2) += exynos9810-star2lte_eur_open_26.dtb

dtb-$(CONFIG_CAMERA_STAR) += exynos9810-starlte_eur_open_26.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
